import { Center, Container, Text, Heading, Stack } from "@chakra-ui/react";
import Head from 'next/head';
import ImageStack from "../components/Stack";

export default function About() {
  return (
    <>
      <Head>
        <title>About | Contemporaries Network</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ImageStack image="/api/mosaic" alt="mosaic" minH="100vh">
          <Container maxW="container.lg" h="full">
            <Center minH="100vh" w="full">
              <Stack spacing="2ex" p="2ex" rounded="xl" bg="blackAlpha.700">
                <Heading>About the project</Heading>
                <Text textAlign="justify">Contemporaries Network is a platform that uses
                  Wikidata and Wikipedia to create a dynamic atlas of
                  prominent personalities who lived about the same
                  time and may or may not have shared a connection.
                </Text>
                <Text textAlign="justify">Ever wondered who people in China listened to
                  when the Beatles were topping the charts in Britain?
                  Would be curious to know how many Prime Ministers
                  post-fascist Italy elected while Franco was still
                  in power in Spain? Not one-hundred percent convinced
                  that Shakespeare wrote his plays himself and would
                  like to check out other candidates for the authorship?
                  Whether it is the times of the Bard, Caudillo or
                  Lennon you are interested in, type the name in the
                  search box, apply the filters and start exploring!
                </Text>
                <Text textAlign="justify">Anyone with an article in Wikipedia could be
                  found and located on a map. 20 of their most notable
                  contemporaries and connections between them will be
                  shown straight away. Dropped pins will mark the places
                  of birth and profile cards will form the entries in
                  the convenient summary table that could be pulled over
                  the map from the bottom of your screen. 20 doesn't
                  sound like enough? No problem, load more people by
                  scrolling down the table and pressing the button.
                  Curious what else the app could do? Then what are you
                  still doing reading this?! Jump to the home page and
                  find out all the amazing features for yourself.
                </Text>

                <Heading>About us</Heading>
                <Text textAlign="justify">
                  Contemporaries Network is a passion project of Katia and
                  Mark. We are a mixed Ukrainian-British couple with a shared
                  interest in history, programming and data analysis.
                  Although, let's be completely honest, programming and data
                  analysis are more than just interests. It is what we do for
                  a living: Mark is a Software Developer, Katia has a degree
                  in AI. But when it comes to history we are enthusiastic
                  amateurs. More often then not, to find the answers to our
                  questions we rely on Wikipedia. We also belong to a
                  generation that wasn't forced to memorise dates of Kings
                  and Queens at school. At best, we could arrange them in
                  order and say that Edward III succeeded to the throne of
                  Edward II and both lived in times of Chaucer. But already
                  couldn't confidently say who ruled over Kyiv at the same
                  time. Same goes for contemporaneous Japanese shoguns or
                  Persian poets.
                </Text>
                <Text textAlign="justify">
                  So we decided to put together our skills and build an app
                  that would satisfy our own curiosity and help with our
                  very “unscientific” enquiries. We called the app Contemporaries
                  Network. If you are reading this, you have probably been
                  asking similar questions and in the process of asking stumbled
                  upon our app. Hope, you will find it useful and entertaining!
                  Have fun!
                </Text>

                <Heading id="contact">Contact Us</Heading>
                <Text textAlign="justify">If you'd like to share feedback with us, we would be
                  very happy to hear from you at contact@contemporariesnetwork.com</Text>
                  
              </Stack>
            </Center>
          </Container>
        </ImageStack >
      </main>
    </>
  )
}