import Head from 'next/head'
import { Center, Container, Heading, Stack, useBreakpointValue, Image, ButtonGroup, Divider } from "@chakra-ui/react";
import { AdvancedSearch } from "../components/AdvancedSearch";
import ImageStack from "../components/Stack";
import Link from '../components/Link';


export default function Home() {
  return (
    <>
      <Head>
        <title>Contemporaries Network</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ImageStack image="/api/mosaic" alt="mosaic" minH="100vh">
          <Container maxW="container.lg" h="full">
            <Center minH="100vh" w="full">
              <Stack direction={useBreakpointValue({ base: "column", md: "row" })} alignItems="center" w="full">
                <Image src="/cnlogo_thin.svg" alt="contemporaries network" w="200px" alignSelf="flex-start" />
                <Stack>
                  <Heading size={useBreakpointValue({ base: "lg", md: "4xl" })}>Contemporaries Network</Heading>
                  <AdvancedSearch width="full" />
                  <Stack direction="row" divider={<Divider mx="2ex" />} w="min-content">
                    <Link href="/about">About</Link>
                    <Link href="/about#contact">Contact</Link>
                  </Stack>
                </Stack>
              </Stack>
            </Center>
          </Container>
        </ImageStack >
      </main >
    </>
  )
}
